name: ci-stable-release

on:
  # push:
  #   branches: [main]
  #   paths:
  #     - "STABLE-RELEASE"
    #  - ".github/workflows/ci-stable-release.yml"
  workflow_dispatch:  

jobs:
  push-stable-version:
    name: Create KubeArmor stable release
    if: github.repository == 'kubearmor/kubearmor'
    runs-on: self-hosted
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: v1.18

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_AUTHTOK }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64,linux/arm64/v8

      - name: Push the stable version of KubeArmor to Docker Hub
        run: STABLE_VERSION=$(cat STABLE-RELEASE) GITHUB_SHA=$GITHUB_SHA ./KubeArmor/build/push_kubearmor.sh stable
